include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false

linter:
  rules:
  - annotate_overrides
  - prefer_relative_imports
  - unnecessary_brace_in_string_interps
